const gendered = (female, male, neutral) => ({ female, male, neutral });

export const BDI_QUESTIONS = [
  {
    text: "Smutek i przygnębienie",
    options: [
      { value: 0, label: gendered("Nie jestem smutna ani przygnębiona.", "Nie jestem smutny ani przygnębiony.", "Nie odczuwam smutku ani przygnębienia.") },
      { value: 1, label: "Często odczuwam smutek i przygnębienie." },
      { value: 2, label: "Stale przeżywam smutek i nie mogę się od niego uwolnić." },
      { value: 3, label: gendered("Jestem stale smutna i nieszczęśliwa. Jest to nie do wytrzymania.", "Jestem stale smutny i nieszczęśliwy. Jest to nie do wytrzymania.", "Stale odczuwam smutek i nieszczęście. Jest to nie do wytrzymania.") },
    ],
  },
  {
    text: "Martwienie się o przyszłość",
    options: [
      { value: 0, label: "Nie przejmuję się zbytnio swoją przyszłością." },
      { value: 1, label: "Często martwię się o swoją przyszłość." },
      { value: 2, label: "Obawiam się, że w przyszłości nic dobrego mnie nie czeka." },
      { value: 3, label: "Czuję, że przyszłość jest beznadziejna i nic tego nie zmieni." },
    ],
  },
  {
    text: "Zaniedbywanie obowiązków",
    options: [
      { value: 0, label: "Sądzę, że nie popełniam większych zaniedbań." },
      { value: 1, label: "Sądzę, że czynię więcej zaniedbań niż inni." },
      { value: 2, label: "Kiedy zastanawiam się nad sobą, widzę mnóstwo błędów i zaniedbań." },
      { value: 3, label: gendered("Jestem zupełnie niewydolna i wszystko robię źle.", "Jestem zupełnie niewydolny i wszystko robię źle.", "Czuję zupełną niewydolność i mam wrażenie, że wszystko robię źle.") },
    ],
  },
  {
    text: "Odczuwanie przyjemności",
    options: [
      { value: 0, label: "To, co robię, sprawia mi przyjemność." },
      { value: 1, label: "Nie cieszy mnie to, co robię." },
      { value: 2, label: "Nic nie daje mi teraz prawdziwego zadowolenia." },
      { value: 3, label: "Nie potrafię przeżywać zadowolenia ani przyjemności. Wszystko mnie nuży." },
    ],
  },
  {
    text: "Poczucie winy",
    options: [
      { value: 0, label: gendered("Nie czuję się winna ani wobec siebie, ani wobec innych.", "Nie czuję się winny ani wobec siebie, ani wobec innych.", "Nie odczuwam winy ani wobec siebie, ani wobec innych.") },
      { value: 1, label: "Dosyć często mam wyrzuty sumienia." },
      { value: 2, label: gendered("Bardzo często czuję, że zawiniłam.", "Bardzo często czuję, że zawiniłem.", "Bardzo często czuję, że ponoszę winę.") },
      { value: 3, label: "Stale mam poczucie winy." },
    ],
  },
  {
    text: "Zasługiwanie na karę",
    options: [
      { value: 0, label: "Sądzę, że nie zasługuję na karę." },
      { value: 1, label: "Sądzę, że zasługuję na karę." },
      { value: 2, label: "Spodziewam się ukarania." },
      { value: 3, label: gendered("Wiem, że jestem karana.", "Wiem, że jestem karany.", "Mam poczucie, że ponoszę karę.") },
    ],
  },
  {
    text: "Zadowolenie z siebie",
    options: [
      { value: 0, label: gendered("Jestem z siebie zadowolona.", "Jestem z siebie zadowolony.", "Odczuwam zadowolenie z siebie.") },
      { value: 1, label: gendered("Nie jestem z siebie zadowolona.", "Nie jestem z siebie zadowolony.", "Nie odczuwam zadowolenia z siebie.") },
      { value: 2, label: "Czuję do siebie niechęć." },
      { value: 3, label: "Nienawidzę siebie." },
    ],
  },
  {
    text: "Poczucie bycia gorszą lub gorszym od innych",
    options: [
      { value: 0, label: gendered("Nie czuję się gorsza od innych ludzi.", "Nie czuję się gorszy od innych ludzi.", "Nie mam poczucia bycia osobą gorszą od innych.") },
      { value: 1, label: gendered("Zarzucam sobie, że jestem nieudolna i popełniam błędy.", "Zarzucam sobie, że jestem nieudolny i popełniam błędy.", "Zarzucam sobie nieudolność i popełnianie błędów.") },
      { value: 2, label: "Stale potępiam siebie za popełnione błędy." },
      { value: 3, label: "Winię siebie za wszystko zło, które istnieje." },
    ],
  },
  {
    text: "Myśli samobójcze i pragnienie śmierci",
    options: [
      { value: 0, label: "Nie myślę o odebraniu sobie życia." },
      { value: 1, label: gendered("Myślę o samobójstwie, ale nie mogłabym tego dokonać.", "Myślę o samobójstwie, ale nie mógłbym tego dokonać.", "Myślę o samobójstwie, ale nie wyobrażam sobie podjęcia działania.") },
      { value: 2, label: "Pragnę odebrać sobie życie." },
      { value: 3, label: "Popełnię samobójstwo, kiedy będzie odpowiednia sposobność." },
    ],
  },
  {
    text: "Płaczliwość",
    options: [
      { value: 0, label: "Nie płaczę częściej niż zwykle." },
      { value: 1, label: "Płaczę częściej niż dawniej." },
      { value: 2, label: "Ciągle chce mi się płakać." },
      { value: 3, label: gendered("Chciałabym płakać, lecz nie jestem w stanie.", "Chciałbym płakać, lecz nie jestem w stanie.", "Pojawia się potrzeba płaczu, ale nie jestem w stanie płakać.") },
    ],
  },
  {
    text: "Rozdrażnienie i nerwowość",
    options: [
      { value: 0, label: gendered("Nie jestem bardziej podenerwowana niż dawniej.", "Nie jestem bardziej podenerwowany niż dawniej.", "Nie odczuwam większego zdenerwowania niż dawniej.") },
      { value: 1, label: gendered("Jestem bardziej nerwowa niż dawniej.", "Jestem bardziej nerwowy niż dawniej.", "Odczuwam większą nerwowość niż dawniej.") },
      { value: 2, label: gendered("Stale jestem zdenerwowana lub rozdrażniona.", "Stale jestem zdenerwowany lub rozdrażniony.", "Stale odczuwam zdenerwowanie lub rozdrażnienie.") },
      { value: 3, label: "Wszystko, co dawniej mnie drażniło, stało się obojętne." },
    ],
  },
  {
    text: "Utrata zainteresowania kontaktami społecznymi",
    options: [
      { value: 0, label: "Ludzie interesują mnie jak dawniej." },
      { value: 1, label: "Interesuję się ludźmi mniej niż dawniej." },
      { value: 2, label: gendered("Utraciłam większość zainteresowania innymi ludźmi.", "Utraciłem większość zainteresowania innymi ludźmi.", "Większość zainteresowania innymi ludźmi zniknęła.") },
      { value: 3, label: gendered("Utraciłam wszelkie zainteresowanie innymi ludźmi.", "Utraciłem wszelkie zainteresowanie innymi ludźmi.", "Nie odczuwam już żadnego zainteresowania innymi ludźmi.") },
    ],
  },
  {
    text: "Trudności w podejmowaniu decyzji",
    options: [
      { value: 0, label: "Podejmuję decyzje łatwo, tak jak dawniej." },
      { value: 1, label: "Częściej niż kiedyś odwlekam podjęcie decyzji." },
      { value: 2, label: "Mam dużo trudności z podjęciem decyzji." },
      { value: 3, label: "Nie jestem w stanie podjąć żadnej decyzji." },
    ],
  },
  {
    text: "Poczucie atrakcyjności",
    options: [
      { value: 0, label: "Sądzę, że wyglądam nie gorzej niż dawniej." },
      { value: 1, label: gendered("Martwię się, że wyglądam staro i nieatrakcyjnie.", "Martwię się, że wyglądam staro i nieatrakcyjnie.", "Martwię się swoim wyglądem i spadkiem atrakcyjności.") },
      { value: 2, label: "Czuję, że wyglądam coraz gorzej." },
      { value: 3, label: gendered("Jestem przekonana, że wyglądam okropnie i odpychająco.", "Jestem przekonany, że wyglądam okropnie i odpychająco.", "Mam przekonanie, że wyglądam okropnie i odpychająco.") },
    ],
  },
  {
    text: "Trudność z wykonywaniem różnych prac i zadań",
    options: [
      { value: 0, label: "Mogę pracować jak dawniej." },
      { value: 1, label: "Z trudem rozpoczynam każdą czynność." },
      { value: 2, label: "Z wielkim wysiłkiem zmuszam się do zrobienia czegokolwiek." },
      { value: 3, label: "Nie jestem w stanie nic robić." },
    ],
  },
  {
    text: "Kłopoty ze snem",
    options: [
      { value: 0, label: "Sypiam dobrze, jak zwykle." },
      { value: 1, label: "Sypiam gorzej niż dawniej." },
      { value: 2, label: "Rano budzę się 1–2 godziny za wcześnie i trudno jest mi ponownie zasnąć." },
      { value: 3, label: "Budzę się kilka godzin za wcześnie i nie mogę zasnąć." },
    ],
  },
  {
    text: "Męczliwość",
    options: [
      { value: 0, label: "Nie męczę się bardziej niż dawniej." },
      { value: 1, label: "Męczę się znacznie łatwiej niż kiedyś." },
      { value: 2, label: "Męczę się wszystkim, co robię." },
      { value: 3, label: gendered("Jestem zbyt zmęczona, aby cokolwiek robić.", "Jestem zbyt zmęczony, aby cokolwiek robić.", "Zmęczenie jest zbyt duże, aby cokolwiek robić.") },
    ],
  },
  {
    text: "Zmiany w apetycie",
    options: [
      { value: 0, label: "Mam apetyt nie gorszy niż dawniej." },
      { value: 1, label: "Mam trochę gorszy apetyt." },
      { value: 2, label: "Mój apetyt jest wyraźnie gorszy." },
      { value: 3, label: "Nie mam w ogóle apetytu." },
    ],
  },
  {
    text: "Utrata masy ciała bez stosowania diety w ostatnim miesiącu",
    options: [
      { value: 0, label: "Nie tracę na wadze." },
      { value: 1, label: "Utrata masy ciała wyniosła więcej niż 2 kg." },
      { value: 2, label: "Utrata masy ciała wyniosła więcej niż 4 kg." },
      { value: 3, label: "Utrata masy ciała wyniosła więcej niż 6 kg." },
    ],
  },
  {
    text: "Martwienie się stanem zdrowia",
    options: [
      { value: 0, label: "Nie martwię się o swoje zdrowie bardziej niż zwykle." },
      { value: 1, label: "Martwię się dolegliwościami, takimi jak rozstrój żołądka, zaparcia lub ból." },
      { value: 2, label: "Stan mojego zdrowia bardzo mnie martwi i często o nim myślę." },
      { value: 3, label: "Tak bardzo martwię się o swoje zdrowie, że nie mogę myśleć o niczym innym." },
    ],
  },
  {
    text: "Zmiana zainteresowania seksem",
    options: [
      { value: 0, label: "Moje zainteresowanie seksem nie uległo zmianie." },
      { value: 1, label: "Sprawy związane z seksem interesują mnie mniej." },
      { value: 2, label: "Seks wyraźnie mniej mnie interesuje." },
      { value: 3, label: gendered("Zupełnie straciłam zainteresowanie seksem.", "Zupełnie straciłem zainteresowanie seksem.", "Zainteresowanie seksem zupełnie zniknęło.") },
    ],
  },
];

export const SCID_QUESTIONS = [
  "Czy unikasz prac lub zadań wymagających kontaktu z dużą liczbą osób?",
  "Czy unikasz nawiązywania przyjaźni, jeśli nie masz pewności, że druga osoba Cię polubi?",
  "Czy trudno Ci otworzyć się nawet wobec bliskich osób?",
  "Czy często martwisz się, że ktoś skrytykuje Cię lub odrzuci w sytuacji towarzyskiej?",
  "Czy zazwyczaj milczysz, kiedy poznajesz nowych ludzi?",
  "Czy uważasz, że pod względem inteligencji, kompetencji lub atrakcyjności wypadasz gorzej niż większość innych ludzi?",
  "Czy boisz się robić rzeczy, które mogą być wyzwaniem, albo próbować czegoś nowego?",
  "Czy na co dzień trudno Ci samodzielnie podejmować proste decyzje bez rady lub wsparcia innych?",
  "Czy polegasz na innych osobach w ważnych sprawach swojego życia, takich jak finanse, opieka nad dziećmi lub miejsce zamieszkania?",
  "Czy masz problem ze sprzeciwianiem się innym, nawet jeśli Twoim zdaniem nie mają racji?",
  "Czy trudno Ci samodzielnie rozpocząć projekt lub zacząć coś robić na własną rękę?",
  "Czy potrzeba opieki ze strony innych jest dla Ciebie tak ważna, że robisz dla nich rzeczy nieprzyjemne lub nierozsądne?",
  "Czy czujesz się nieswojo, kiedy nie ma przy Tobie innych osób?",
  "Czy po zakończeniu związku od razu szukasz kogoś, kto się o Ciebie zatroszczy?",
  "Czy często martwisz się, że zabraknie Ci bliskiej osoby i trzeba będzie samodzielnie się o siebie zatroszczyć?",
  "Czy spędzasz dużo czasu na szczegółach, porządku, organizacji lub tworzeniu list i planów?",
  "Czy masz trudności z kończeniem zadań, ponieważ poświęcasz bardzo dużo czasu na wykonanie ich dokładnie zgodnie ze swoimi oczekiwaniami?",
  "Czy praca lub potrzeba wydajności pochłaniają Cię w bardzo dużym stopniu?",
  "Czy masz wysokie standardy dotyczące tego, co jest dobre, a co złe?",
  "Czy trudno Ci wyrzucić rzeczy, ponieważ mogą się jeszcze kiedyś przydać?",
  "Czy trudno Ci pracować z innymi lub prosić o pomoc, jeśli te osoby nie działają ściśle według Twoich poleceń?",
  "Czy trudno Ci wydawać pieniądze na siebie lub innych ludzi?",
  "Czy kiedy już coś zaplanujesz, trudno Ci zmienić plany?",
  "Czy inni ludzie mówią, że jesteś osobą upartą?",
  "Czy często masz poczucie, że inni Cię wykorzystują, krzywdzą lub okłamują?",
  "Czy uważasz się za bardzo skrytą osobę, która rzadko zwierza się innym?",
  "Czy uważasz, że lepiej, aby ludzie nie wiedzieli o Tobie zbyt wiele, ponieważ mogliby to wykorzystać przeciwko Tobie?",
  "Czy często czujesz, że ludzie Ci grożą lub obrażają Cię tym, co mówią albo jak postępują?",
  "Czy chowasz urazy i niechętnie wybaczasz osobom, które Cię zraniły lub obraziły?",
  "Czy jest wiele osób, którym nie możesz wybaczyć czegoś zrobionego lub powiedzianego dawno temu?",
  "Czy łatwo wpadasz w gniew lub atakujesz kogoś w odpowiedzi na krytykę albo zniewagę?",
  "Czy zdarzało Ci się podejrzewać żonę, męża lub osobę partnerską o zdradę?",
  "Czy kiedy widzisz rozmawiających ludzi, często myślisz, że rozmawiają o Tobie?",
  "Czy wśród ludzi często masz wrażenie, że inni Cię obserwują?",
  "Czy często masz wrażenie, że słowa piosenki albo scena w filmie lub telewizji są skierowane właśnie do Ciebie?",
  "Czy jesteś osobą przesądną?",
  "Czy kiedykolwiek pojawiło się u Ciebie poczucie, że możesz sprawić, aby coś się stało, jedynie myśląc o tym lub wypowiadając życzenie?",
  "Czy masz za sobą osobiste doświadczenia z mocami nadprzyrodzonymi?",
  "Czy wierzysz, że masz szósty zmysł pozwalający wiedzieć i przewidywać różne rzeczy?",
  "Czy często masz wrażenie, że wszystko wokół jest nierealne, odczuwasz oddzielenie od ciała albo umysłu lub obserwujesz swoje myśli czy ruchy z zewnątrz?",
  "Czy często widzisz rzeczy, których inni ludzie nie widzą?",
  "Czy często słyszysz głos łagodnie wypowiadający Twoje imię?",
  "Czy zdarzyło Ci się czuć, że jakaś osoba lub siła jest blisko, chociaż nikogo nie było widać?",
  "Czy masz niewiele naprawdę bliskich osób poza najbliższą rodziną?",
  "Czy często denerwujesz się wśród osób, których nie znasz dobrze?",
  "Czy posiadanie przyjaciół, osoby partnerskiej lub bliskich relacji z rodziną NIE jest dla Ciebie ważne?",
  "Czy prawie zawsze wolisz robić różne rzeczy samodzielnie, a nie z innymi ludźmi?",
  "Czy Twoje zainteresowanie kontaktami seksualnymi z inną osobą jest małe lub żadne?",
  "Czy niewiele rzeczy sprawia Ci przyjemność?",
  "Czy NIE jest dla Ciebie ważne, co ludzie o Tobie myślą?",
  "Czy rzadko doświadczasz silnych uczuć, takich jak złość lub radość?",
  "Czy lubisz być w centrum uwagi?",
  "Czy często flirtujesz?",
  "Czy często kogoś podrywasz?",
  "Czy lubisz zwracać na siebie uwagę sposobem ubierania się lub wyglądem?",
  "Czy masz skłonność do zachowywania się i mówienia w sposób teatralny oraz bardzo emocjonalny?",
  "Czy Twoja wrażliwość emocjonalna jest większa niż u większości ludzi, na przykład płaczesz przy smutnej historii?",
  "Czy często zmieniasz zdanie pod wpływem osób, z którymi przebywasz, albo tego, co właśnie czytasz lub oglądasz?",
  "Czy odczuwasz przyjaźń lub szczególną bliskość wobec osób świadczących Ci usługi, na przykład hydraulika, mechanika lub lekarza?",
  "Czy uważasz, że jesteś osobą ważniejszą, bardziej utalentowaną lub odnoszącą większe sukcesy niż większość ludzi?",
  "Czy ktoś mówił Ci, że masz zbyt wysokie mniemanie o sobie?",
  "Czy dużo myślisz o władzy, sukcesie lub uznaniu, które kiedyś osiągniesz?",
  "Czy rozmyślasz o idealnej miłości, której kiedyś doświadczysz?",
  "Czy kiedy masz jakąś sprawę, zawsze domagasz się spotkania z osobą na najwyższym szczeblu organizacji?",
  "Czy starasz się spędzać czas z osobami ważnymi lub wpływowymi?",
  "Czy jest dla Ciebie ważne, aby ludzie zwracali na Ciebie uwagę i Cię podziwiali?",
  "Czy uważasz, że zasługujesz na specjalne traktowanie albo że inni powinni automatycznie robić to, czego chcesz?",
  "Czy często przedkładasz własne potrzeby nad potrzeby innych?",
  "Czy inni skarżą się, że wykorzystujesz ludzi?",
  "Czy uważasz, że potrzeby i uczucia innych ludzi nie są tak naprawdę Twoim problemem?",
  "Czy często problemy innych osób są dla Ciebie nudne?",
  "Czy ludzie skarżyli się, że ich nie słuchasz lub nie dbasz o ich uczucia?",
  "Czy kiedy widzisz osobę, która odniosła sukces, czujesz, że to Tobie bardziej się on należał?",
  "Czy czujesz, że inni są wobec Ciebie zawistni?",
  "Czy uważasz, że bardzo niewiele osób jest wartych Twojej uwagi i czasu?",
  "Czy inni ludzie skarżyli się, że zachowujesz się zbyt wyniośle lub arogancko?",
  "Czy kiedy myślisz, że bliska osoba chce Cię opuścić, wpadasz w panikę?",
  "Czy w Twoich relacjach z bliskimi ludźmi zdarzają się gwałtowne wzloty i upadki?",
  "Czy Twoje poczucie tego, kim jesteś, często dramatycznie się zmienia?",
  "Czy zachowujesz się inaczej wobec różnych osób lub w różnych sytuacjach i czasem nie wiesz, kim naprawdę jesteś?",
  "Czy w Twoim życiu zaszło wiele gwałtownych zmian dotyczących celów, planów kariery lub przekonań?",
  "Czy w Twoim życiu zaszło wiele nagłych zmian dotyczących osób, z którymi się przyjaźnisz, lub tożsamości seksualnej?",
  "Czy często zachowujesz się impulsywnie?",
  "Czy zdarzyło Ci się próbować zrobić sobie krzywdę, podjąć próbę samobójczą albo grozić takim działaniem?",
  "Czy zdarzyło Ci się celowo przypalać, ciąć lub w inny sposób robić sobie krzywdę?",
  "Czy Twój nastrój w ciągu dnia często zmienia się zależnie od tego, co dzieje się w Twoim życiu?",
  "Czy często czujesz wewnętrzną pustkę?",
  "Czy często miewasz wybuchy gniewu lub złość tak silną, że trudno Ci nad sobą panować?",
  "Czy w złości bijesz ludzi lub rzucasz przedmiotami?",
  "Czy nawet drobiazgi wywołują Twój gniew?",
  "Czy przy bardzo silnym zdenerwowaniu pojawia się u Ciebie podejrzliwość wobec innych, odłączenie od ciała albo poczucie nierealności otoczenia?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się znęcać nad innymi dziećmi, grozić im albo je straszyć?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się wszczynać bójki?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się skrzywdzić kogoś przy użyciu broni lub grozić komuś bronią?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się okrutnie traktować kogoś i powodować ból fizyczny lub cierpienie?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się celowo skrzywdzić zwierzę?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się kogoś okraść, napaść albo zabrać coś przy użyciu przemocy lub gróźb?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się zmusić kogoś do zachowań o charakterze seksualnym?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się wzniecić pożar?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się celowo niszczyć cudze rzeczy?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się włamać do czyjegoś mieszkania, budynku lub samochodu?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się często okłamywać lub nabierać innych, aby coś dostać albo uniknąć obowiązku?",
  "Czy przed ukończeniem 15 lat zdarzało Ci się kraść w sklepie lub innym miejscu albo podrabiać czyjś podpis dla pieniędzy?",
  "Czy przed ukończeniem 15 lat zdarzyło Ci się uciec z domu lub spędzić noc poza domem?",
  "Czy przed ukończeniem 13 lat często zdarzało Ci się zostawać poza domem znacznie dłużej niż było ustalone?",
  "Czy przed ukończeniem 13 lat często zdarzało Ci się wagarować?",
];
